# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd6f1dc016ad07fec4ed49f41d3a09a0dd20d4fc613d181ddced1fb07258c886de0d6bb03866135ed3374ebd64255cfebe45077f1fb613a853235c6e3c7bc51

test:
  secret_key_base: 1de441af8ebe823fa6e1e2dad61a13dfc8517f9e5fb4a71dc2c07d6bcc438010976e47cae46768ac0916ef07496c978f44dc4347d604e86ce6b118848213a97b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
